### PR TITLE
fix(Server): cascade stats options

### LINKED ISSUE #1557: No respect, no respect at all! (for stats.warningsFilter 😉)
* Operating System: mac OS Sierra 10.12.6
* Node Version: 6.11.1
* NPM Version: 3.10.10
* webpack Version: 4.19.0
* webpack-dev-server Version: 3.1.8

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

**webpack.config_.dev_.js**
```js
  //...
devServer: {
    host: '0.0.0.0',
    port: WEBPACK_PORT,
    watchOptions: {
      aggregateTimeout: 300,
      poll: true
    },
    stats: {
      assets: false,
      children: false,
      colors: true,
      version: false,
      hash: false,
      timings: true,
      chunks: false,
      chunkModules: false,
      warningsFilter: '[mini-css-extract-plugin]'
    },
    headers: {
      'Access-Control-Allow-Origin': '*'
    }
```

Webpack config stats docs I'm going off of:
https://webpack.js.org/configuration/stats/#stats

WDS stats docs:
https://webpack.js.org/configuration/dev-server/#devserver-stats-

### Expected Behavior
While using `stats.warningsFilter` in my configuration, then it would be respected by webpack-dev-server, and that errors of anything from `stats.warningsFilter` would be filtered out and not posted to my browser's console. The closest to addressing logging that I can find in your code is [this line](https://github.com/webpack/webpack-dev-server/blob/55398b5de17b9a845b1ee5aaa90bb2002c25ddfb/bin/webpack-dev-server.js#L179), or several other lines that check for `stats.colors` from the same file.
Note: I _am_ certain that my stats are connected correctly, because setting my `stats.colors` to false turns the colors off.

### Actual Behavior
When adding `warningsFilter: '[mini-css-extract-plugin]'` to my config, errors from Webpack-Dev-Middleware are respected, and I no longer see them:
```
[webpack] ℹ ｢wdm｣: Compiled with warnings.
```
However, I am still getting my warnings in the browser's console:

screen shot 2018-11-01 at 3 41 11 pm

Which is originating from https://github.com/webpack/webpack-dev-server/blob/55398b5de17b9a845b1ee5aaa90bb2002c25ddfb/client-src/default/index.js#L145

### For Bugs; How can we reproduce the behavior?
Hmm I guess you'd need to set up a warning that you would try to filter out with your webpack config. Open browser console, errors persist with each page reload.

Note: when I update webpack-dev-server to latest version (3.1.10), problem still persists.

Thank you in advance!

### PR DESCRIPTION
**Pull request by yoannmoinet**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Will work on it if really needed.

### Motivation / Use-Case

We get flooded by warnings in the console.

### Additional Info

Fixes #1557

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Also please accept CLA

**Comment by yoannmoinet** [comment]
Actually this won't work if we use a string for `options.stats` like `errors-only`.
Will update and add tests.

**Comment by yoannmoinet** [comment]
@evilebottnawi I've refactored the code to also accepts strings.
I tried to write tests, but I'm not sure where to begin.

I tried creating a new `test/Server.test.js` but I can't make any test pass, I think I'm going in the wrong direction.
Would you help please?

**Comment by yoannmoinet** [comment]
Can someone help with the tests (cc @evilebottnawi) ?

Here's what I tried with `Server.test.js` but I've been unsuccessful.

```javascript
'use strict';

const webpack = require('webpack');
const Server = require('../lib/Server');
const config = require('./fixtures/simple-config/webpack.config');

const allStats = [
  {},
  // eslint-disable-next-line
  undefined,
  'errors-only',
  {
    assetsSort: "size"
  }
];

describe('Server', () => {
  allStats.forEach((s) => {
    it('should cascade stats options', (done) => {
      const compiler = webpack(Object.assign({}, config, s && { stats: s }));
      const server = new Server(compiler, {});
      const next = () => {
        const localStats = server.getStats(server._stats);

        if(!s || !Object.keys(s).length) {
          expect(localStats).toBe(server.DEFAULT_STATS);
        } else {
          expect(localStats).not.toBe(server.DEFAULT_STATS);
        }

        server.close(() => {
          done();
        });
      };
      server.listen(8080, 'localhost', (err) => {
        if (err) return next(err);
        next();
      });
    });
  });
});
```

**Comment by yoannmoinet** [comment]
@evilebottnawi from what I understand, what you pointed to is if we want to use webpack's stats config if none is given to devServer's config, as a fallback.
I've added a commit that does just that, but on its own, it won't fix the bug, we still need the change in `Server.js` for it to cascade into the browser's console.

File: lib/Server.js [hunk 1]
```diff
@@ -91,6 +82,15 @@ class Server {
...
 
+    this.stats = options.stats;
+    this.DEFAULT_STATS = {
+      all: false,
+      hash: true,
+      assets: true,
+      warnings: true,
+      errors: true,
+      errorDetails: false,
+    };
```
Comment (evilebottnawi) [inline lib/Server.js]: Let's avoid `this.DEFAULT_STATS` (because it should be as private property)

**Comment by hiroppy** [comment]
The snapshot test is currently failing.

File: lib/Server.js (hunk 1 above)
Comment (yoannmoinet) [reply lib/Server.js]: I needed it for the tests.
Should I add them to the Server's prototype then?

Comment (evilebottnawi) [reply lib/Server.js]: Can you provide link where you need it for test? You already have `getStats` method

**Comment by yoannmoinet** [comment]
> Loooks good, need add tests for `warningsFilter`

@evilebottnawi I'm not sure what you're asking for.

> The snapshot test is currently failing.

@hiroppy indeed, I cannot reproduce locally though, so I don't know what to look for.

**Comment by evilebottnawi** [comment]
@yoannmoinet we need add tests for `stats` https://webpack.js.org/configuration/stats/ (`warningsFilter` option) to ensure we fix problem (what is written in issue)

**Comment by yoannmoinet** [comment]
@evilebottnawi oh yes, I'm working on this right now 😉 
I wasn't sure we were talking about the same thing 👍

**Comment by yoannmoinet** [comment]
@evilebottnawi here you go, I've added test for the Server.

File: lib/Server.js (hunk 1 above)
Comment (yoannmoinet) [reply lib/Server.js]: [this is where I'm using it](https://github.com/webpack/webpack-dev-server/pull/1665/files#diff-7775e181de5f32a001a1636103e7008fR33)

**Comment by yoannmoinet** [comment]
I'm not sure I understand Travis' errors.

**Comment by yoannmoinet** [comment]
can you help with the failing task in Travis @evilebottnawi please?

**Comment by evilebottnawi** [comment]
@yoannmoinet try to do rebase

**Comment by yoannmoinet** [comment]
I'm not sure what kind of test I'm supposed to add following the `codecov/patch` task failing.
I felt like I added all the tests needed.
cc @evilebottnawi

File: lib/Server.js [hunk 2]
```diff
@@ -668,6 +674,10 @@ class Server {
     }, this);
   }
 
+  getStats(statsObj) {
+    return statsObj.toJson(this.stats);
+  }
```
Comment (evilebottnawi) [inline lib/Server.js]: Let's move
```
this.stats =
      options.stats && Object.keys(options.stats).length
        ? options.stats
        : Server.DEFAULT_STATS;
```

logic here, we don't need new property like `stats`

Comment (yoannmoinet) [reply lib/Server.js]: Oh, good point, will update.

Comment (yoannmoinet) [reply lib/Server.js]: I still need to keep the property to have access to `options.stats`.

Comment (yoannmoinet) [reply lib/Server.js]: Not sure it would be useful to move the logic since I still need to keep that `this.stats` so I can use `options.stats` in `getStats()`.
What do you think @evilebottnawi ?

Comment (evilebottnawi) [reply lib/Server.js]: Yep, you are right, we should rewrite this in next major release
