### PR TITLE
fix: add client.overlay.runtimeErrors options

### LINKED ISSUE #4771: Webpack-dev-server version 4.12.0 causing compile errors in application
### Bug report
Webpack-dev-server version 4.12.0 causes compile errors in application on browser viewport resize

### Actual Behavior

We run an application which uses webpack-dev-server 4.12.0 as a dependency. With this version of webpack-dev-server, whenever we resize the browser viewport in our application (e.g. by opening developer tools), an error overlay pops up stating "ResizeObserver loop limit exceeded". _This behaviour does not occur in the exact same version of the application that uses webpack-dev-server version 4.11.1_.

image

### Expected Behavior

The error should not appear when resizing the browser viewport in any way.

### How Do We Reproduce?

- Run an application that uses webpack-dev-server version 4.12.0
- Open developer tools in the browser

image

image

image

### PR DESCRIPTION
**Pull request by malcolm-kee**
- [x] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

Reported in #4771

fixes https://github.com/webpack/webpack-dev-server/issues/4774
fixes #4771

- Added `client.overlay.runtimeErrors` options - default to `true`.

### CODE REVIEW

**Comment by malcolm-kee** [comment]
@alexander-akait I added the fix and verified it by testing it manually. 

If automated test is a must-have I'll have to do it tomorrow as I'm very tired now (it's 3am here).

File: client-src/index.js [hunk 1]
```diff
@@ -118,9 +118,15 @@ self.addEventListener("beforeunload", () => {
 const trustedTypesPolicyName =
   typeof options.overlay === "object" && options.overlay.trustedTypesPolicyName;
 
-const overlay = createOverlay({
-  trustedTypesPolicyName,
-});
+const overlay = options.overlay
```
Comment (crobinson42) [inline client-src/index.js:121]: @malcolm-kee  this is not sufficient. You are only checking if `options.overlay` is truthy. All options need to be passed into the `createOverlay()` function. The `overlay` options are `errors: boolean` & `warnings: boolean`. 

Then, the `show()` function in `overlay.js` needs to check if the `type` is "warning" or "error" and compare the passed options.

Comment (alexander-akait) [reply client-src/index.js:121]: Yeah, we have before https://github.com/webpack/webpack-dev-server/blob/v4.11.1/client-src/index.js#L253

Comment (malcolm-kee) [reply client-src/index.js:118]: @crobinson42 good catch!

I just pushed a fix so that runtime error check the options as well.

For build error/warning, it's already handled:

- (errors) https://github.com/webpack/webpack-dev-server/blob/master/client-src/index.js#L297
- (warnings) https://github.com/webpack/webpack-dev-server/blob/master/client-src/index.js#L265

Comment (alexander-akait) [reply client-src/index.js:118]: Testa are failed, can you look what is wrong (no rush), I think today after rest we will fix all issues

File: client-src/index.js [hunk 2]
```diff
@@ -115,12 +115,23 @@ self.addEventListener("beforeunload", () => {
...
-
-const overlay = createOverlay({
-  trustedTypesPolicyName,
-});
+const overlay = options.overlay
+  ? createOverlay(
+      typeof options.overlay === "object"
+        ? {
+            trustedTypesPolicyName: options.overlay.trustedTypesPolicyName,
+            catchRuntimeError: options.overlay.errors,
```
Comment (alexander-akait) [inline client-src/index.js:123]: What abour warning?

Comment (alexander-akait) [inline client-src/index.js:123]: Also ideally we need a new option for such stuff, i.e. `catchRuntimeError`, because as you can see some application works in very differents envs and it can be errors outside own application

File: client-src/index.js [hunk 3]
```diff
@@ -80,6 +80,7 @@ if (parsedResourceQuery.overlay) {
     options.overlay = {
       errors: true,
       warnings: true,
+      runtimeErrors: true,
```
Comment (malcolm-kee) [inline client-src/index.js:83]: Default it to true.

**Comment by malcolm-kee** [comment]
@alexander-akait I'm having problem to run the test for webpack5 to update snapshot. I tried to run it it will stuck without any reason. It's the same with `master` branch so my setup has issue. 😅

**Comment by alexander-akait** [comment]
I will update tests don't worry

**Review by alexander-akait — APPROVED** [review]
