### PR TITLE
fix: compatibility with old browsers

### LINKED ISSUE #4543: Version 4.10.0 breaks compatibility with older browsers that do not have Object.entries
### Actual Behavior

Old browsers throws exception on 4.10.0: no method Object.entries
Version 4.9.x works.

The problem is with this file:
https://github.com/webpack/webpack-dev-server/blob/216e3cbe62dc90b9345995cb4f33ca9dd7b6aaba/client-src/utils/log.js#L22

core-js polyfill does not work because this file was loaded before it.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
  System:
    OS: Linux 5.15 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-5020U CPU @ 2.20GHz
    Memory: 5.07 GB / 7.67 GB
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    npm: 8.15.1 - /usr/bin/npm
  Browsers:
    Firefox: 103.0.2
  Packages:
    css-loader: ^6.5.1 => 6.7.1 
    file-loader: ^6.2.0 => 6.2.0 
    postcss-loader: ^7.0.1 => 7.0.1 
    replace-bundle-webpack-plugin: ^1.0.0 => 1.0.0 
    source-map-loader: ^4.0.0 => 4.0.0 
    style-loader: ^3.3.1 => 3.3.1 
    ts-loader: ^9.2.6 => 9.3.1 
    url-loader: ^4.1.1 => 4.1.1 
    webpack: ^5.74.0 => 5.74.0 
    webpack-bundle-analyzer: ^4.5.0 => 4.6.0 
    webpack-cli: ^4.10.0 => 4.10.0 
    webpack-dev-server: ~4.10.0 => 4.10.0

### PR DESCRIPTION
**Pull request by snitin315**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Already present.

### Motivation / Use-Case

Fix #4543

`Object.keys` is compatible with IE9,10, and 11 - https://caniuse.com/?search=object.keys

### Breaking Changes

No

### Additional Info
No

### CODE REVIEW

File: client-src/utils/log.js [hunk 1]
```diff
@@ -27,8 +27,8 @@ const logEnabledFeatures = (features) => {
   let logString = "Server started:";
 
   // Server started: Hot Module Replacement enabled, Live Reloading enabled, Overlay disabled.
-  for (const [key, value] of Object.entries(features)) {
-    logString += ` ${key} ${value ? "enabled" : "disabled"},`;
+  for (const key of Object.keys(features)) {
```
Comment (alexander-akait) [inline client-src/utils/log.js:30]: Still new syntax https://caniuse.com/mdn-javascript_statements_for_of, let rewrite on simple loop

Comment (snitin315) [reply client-src/utils/log.js:30]: Actually, this will be converted to for loop by babel:

Screenshot 2022-08-27 at 6 51 03 AM

Comment (snitin315) [reply client-src/utils/log.js]: Fixed.

**Review by alexander-akait — APPROVED** [review]
