### PR TITLE
fix(server): fallthrough non `GET` and `HEAD` request to routes defined in after option

### LINKED ISSUE #2370: The [before] and [after] option hook not allow http POST request?
Operating System: Mac OS 10.15.2
Node Version: 13.5.0
NPM Version: 6.13.4
webpack Version: 4.41.4
webpack-dev-server Version: 3.10.1
Browser: Chrome

! This is a bug

I was writing an express middleware, try to send request dev server, but it not allowed!
** But webpack-dev-server 3.9.0 work fine!!!**

Screen Shot 2019-12-25 at 11 22 09 AM

### PR DESCRIPTION
**Pull request by jvasseur**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

Before #2150, non-GET request where forwarded to any middleware defined in the after option, since #2150, they are handled by `serve-index` instead that always reply with a 405 error.

This fix issue #2370.

### Breaking Changes

No

### Additional Info

Closes #2370

### CODE REVIEW

File: lib/Server.js [hunk 1]
```diff
@@ -390,13 +390,25 @@ class Server {
 
     if (Array.isArray(contentBase)) {
       contentBase.forEach((item) => {
-        this.app.use(contentBasePublicPath, serveIndex(item));
+        this.app.use(contentBasePublicPath, (req, res, next) => {
+          if (req.method !== 'GET') {
```
Comment (evilebottnawi) [inline lib/Server.js]: Not sure it is good solution, developers can want to handle `GET` in own middleware too

Comment (jvasseur) [reply lib/Server.js]: AFAIK, `serve-index` let `GET` request that it can't handle fall-back to the next middleware, it's just non-GET request that are blindly replied as `405`.

This is basically a revert of the change from `app.get` to `app.use` done in #2150 while still keeping the `contentBasePublicPath` feature.

**Comment by jvasseur** [comment]
@evilebottnawi the `serve-static` doesn't exhibit this problem because it already forward non-GET request to the next middleware : https://github.com/expressjs/serve-static/blob/master/index.js#L73-L76

**Comment by iamandrewluca** [comment]
I'm taking a look into `serve-index` implementation

File: lib/Server.js (hunk 1 above)
Comment (iamandrewluca) [reply lib/Server.js]:
```suggestion
          if (req.method !== 'GET' && req.method !== 'HEAD') {
```

File: lib/Server.js [hunk 2]
```diff
@@ -390,13 +390,25 @@ class Server {
...
+          serveIndex(item)(req, res, next);
+        });
       });
     } else if (
       typeof contentBase !== 'number' &&
       !isAbsoluteUrl(String(contentBase))
     ) {
-      this.app.use(contentBasePublicPath, serveIndex(contentBase));
+      this.app.use(contentBasePublicPath, (req, res, next) => {
+        if (req.method !== 'GET') {
```
Comment (iamandrewluca) [inline lib/Server.js]:
```suggestion
        if (req.method !== 'GET' && req.method !== 'HEAD') {
```

Comment (evilebottnawi) [reply lib/Server.js]: Can you clarify?

**Comment by iamandrewluca** [comment]
`serve-static` has `fallthrough`, but we don't use it in our case, it must be added.
`serve-index` [does not have ](https://github.com/expressjs/serve-index/pull/61) `fallthrough`, and I agree with the workaround in this PR.

@jvasseur also make sure you check also for `HEAD` method
```js
if (req.method !== 'GET' && req.method !== 'HEAD') {
// ...
```

**Comment by jvasseur** [comment]
@iamandrewluca `true` is already the [default value](https://github.com/expressjs/serve-static/blob/master/index.js#L51) for the fallthrough parameter of `serve-static`.

I've added the check for `HEAD` in the code.

**Comment by iamandrewluca** [comment]
recommend to rename PR into
```
fix(server): fallthrough non `GET` and `HEAD` request forward to routes defined in after option
```

**Comment by iamandrewluca** [comment]
@jvasseur pls add a comment in code, that `serve-index` does not fallthrough like `serve-static`

**Comment by jvasseur** [comment]
@iamandrewluca done

**Comment by iamandrewluca** [comment]
@jvasseur add at the end of PR description this. It will automatically close the issue when PR is merged.
```
Closes #2370
```

**Comment by jvasseur** [comment]
Done

**Comment by hiroppy** [comment]
Thanks!

**Comment by iamandrewluca** [comment]
Released in https://github.com/webpack/webpack-dev-server/releases/tag/v3.10.2
