### PR TITLE
Fixes #1805: Allow symlinks for devServer.https options

### LINKED ISSUE #1805: devServer.https.cert results in error if symlink used
Discovered an issue when setting the devServer.https.cert value to the path of a symlink. Even though the destination of the symlink is a valid certificate, webpack will instead treat the filepath itself as the certificate which naturally fails.

I plan to submit a PR with a fix in the next few days by adding `fs.realpath(...)` before doing lstat on the file.

https://github.com/webpack/webpack-dev-server/blob/cf4d0d07b8ffba9d28cd627b48f74e5f4f307fc6/lib/Server.js#L606

```
/home/myuser/workspace/myproject/node_modules/webpack-dev-server/bin/webpack-dev-server.js:168
    throw err;
    ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:88:17)
    at Server (_tls_wrap.js:819:25)
    at Server (https.js:60:14)
    at Server._init (/home/myuser/workspace/myproject/node_modules/spdy/lib/spdy/server.js:62:10)
    at new Server (/home/myuser/workspace/myproject/node_modules/spdy/lib/spdy/server.js:25:10)
    at Function.create (/home/myuser/workspace/myproject/node_modules/spdy/lib/spdy/server.js:30:12)
    at Object.create [as createServer] (/home/myuser/workspace/myproject/node_modules/spdy/lib/spdy/server.js:286:27)
    at new Server (/home/myuser/workspace/myproject/node_modules/webpack-dev-server/lib/Server.js:655:45)
    at startDevServer (/home/myuser/workspace/myproject/node_modules/webpack-dev-server/bin/webpack-dev-server.js:160:14)
    at processOptions (/home/myuser/workspace/myproject/node_modules/webpack-dev-server/bin/webpack-dev-server.js:113:5)
    at Object.<anonymous> (/home/myuser/workspace/myproject/node_modules/webpack-dev-server/bin/webpack-dev-server.js:229:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject@0.0.1 start: `ant generate-proctor-js && WEBPACK_PROXY=1 webpack-dev-server --config webpack.config.js --progress --colors --inline --https --cert /etc/ssl/certs/My-Dev-Cert.pem --key /etc/ssl/private/My-Dev-Cert.key`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myproject@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
```

### PR DESCRIPTION
**Pull request by chaos-git**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

Solves issue #1805: https://github.com/webpack/webpack-dev-server/issues/1805

There are cases where files that are being referred to in the webpack devServer config are actually symlinks. The documentation does not state that symlinks are not supported, and I don't personally see a reason why symlinks shouldn't be supported. By including this PR, users of webpack dev server can use symlinks for their certificate paths `devServer.https.cert` rather than having to read the file into buffer before starting the devServer.

If the reviewers believe this shouldn't be supported, then I'd ask that the documentation be updated to say symlinks are not supported. It wasn't immediately clear that the issue was related to symlinks. The error messaging was purely around being unable to parse the certificate, but that was only because webpack code was treating the filepath itself as the certificate.

### Breaking Changes

None

### Additional Info

None

### CODE REVIEW

**Comment by chaos-git** [comment]
> Please run this test only on linux

```
$ npm test
...
-----------------------|----------|----------|----------|----------|-------------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------|----------|----------|----------|----------|-------------------|
All files              |     87.7 |    83.11 |    87.64 |    87.62 |                   |
 lib                   |    83.25 |    76.08 |    85.25 |    83.21 |                   |
  Server.js            |    83.25 |    76.08 |    85.25 |    83.21 |... ,986,1024,1025 |
 lib/utils             |    96.19 |    92.04 |    92.86 |    96.14 |                   |
  addEntries.js        |      100 |    97.67 |      100 |      100 |                 7 |
  createCertificate.js |    66.67 |      100 |        0 |    66.67 |                 6 |
  createConfig.js      |    94.68 |    93.75 |    66.67 |    94.62 |    34,63,65,68,95 |
  createDomain.js      |      100 |    81.25 |      100 |      100 |              9,13 |
  createLogger.js      |     87.5 |    83.33 |      100 |     87.5 |                 9 |
  defaultTo.js         |      100 |      100 |      100 |      100 |                   |
  findPort.js          |    94.12 |    83.33 |      100 |    94.12 |                21 |
  updateCompiler.js    |      100 |    81.25 |      100 |      100 |          30,37,59 |
-----------------------|----------|----------|----------|----------|-------------------|

Test Suites: 23 passed, 23 total
Tests:       252 passed, 252 total
Snapshots:   95 passed, 95 total
Time:        26.419s
Ran all test suites.
```
```
$ cat /proc/version
Linux version 4.15.0-45-generic (buildd@lgw01-amd64-031) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
```

**Comment by chaos-git** [comment]
Tests pass on MacOS 10

```
$ npm test
...
-----------------------|----------|----------|----------|----------|-------------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------|----------|----------|----------|----------|-------------------|
All files              |    87.54 |    82.89 |    87.64 |    87.46 |                   |
 lib                   |       83 |    75.69 |    85.25 |    82.96 |                   |
  Server.js            |       83 |    75.69 |    85.25 |    82.96 |... ,986,1024,1025 |
 lib/utils             |    96.19 |    92.04 |    92.86 |    96.14 |                   |
  addEntries.js        |      100 |    97.67 |      100 |      100 |                 7 |
  createCertificate.js |    66.67 |      100 |        0 |    66.67 |                 6 |
  createConfig.js      |    94.68 |    93.75 |    66.67 |    94.62 |    34,63,65,68,95 |
  createDomain.js      |      100 |    81.25 |      100 |      100 |              9,13 |
  createLogger.js      |     87.5 |    83.33 |      100 |     87.5 |                 9 |
  defaultTo.js         |      100 |      100 |      100 |      100 |                   |
  findPort.js          |    94.12 |    83.33 |      100 |    94.12 |                21 |
  updateCompiler.js    |      100 |    81.25 |      100 |      100 |          30,37,59 |
-----------------------|----------|----------|----------|----------|-------------------|

Test Suites: 23 passed, 23 total
Tests:       251 passed, 251 total
Snapshots:   95 passed, 95 total
Time:        52.502s
Ran all test suites.
```
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

**Comment by chaos-git** [comment]
Unsure why the test is failing on AppVeyor.. looking in to it..

**Comment by evilebottnawi** [comment]
Because windows doesn't support symbolic links

**Comment by evilebottnawi** [comment]
> Please run this test only on linux

You need add check `if (isLinux()) { /* HERE CODE OF TESTS */} ``

**Comment by chaos-git** [comment]
Trying to reproduce the steps that AppVeyor takes.. and I can't seem reproduce the failed test on my Linux box. Any ideas?

```
 PASS  test/Https.test.js
```

```
$ git remote show origin

* remote origin
  Fetch URL: https://github.com/webpack/webpack-dev-server.git
  Push  URL: https://github.com/webpack/webpack-dev-server.git
  HEAD branch: master
  Remote branches:
    master                                tracked
    renovate/patch-all-patch-dependencies tracked
    renovate/strip-ansi-5.x               tracked
    renovate/yargs-13.x                   tracked
    v2                                    tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

```
$ git log --pretty=oneline | head
694b26509fd223b012619f42a14fd59504659b78 Merge 2aa5cbd4a92b796c2701ca1baf5ab4cd18cfe135 into cf4d0d07b8ffba9d28cd627b48f74e5f4f307fc6
2aa5cbd4a92b796c2701ca1baf5ab4cd18cfe135 test(https): add symlinks test
c17be78404ed797125833ecf287233673c6173f7 fix: allow symlinks for devServer.https values (#1805)
cf4d0d07b8ffba9d28cd627b48f74e5f4f307fc6 fix: only add client entry to web targets (#1775)
58d168237508bf419714d155496b954b98681d04 feat: add sockPort option (#1792)
11bda15bfd11b8073a5edc99235449a0c93615a5 chore(deps): update dependency eslint-plugin-import to v2.17.1 (#1798)
b75188d5faa98abc2c6cd642500dd872bed7598a chore(deps): update dependency nyc to v14 (#1800)
59773d39875fecca5df0b25d61a75d1801c3a9b0 chore(deps): update all minor dependencies (#1790)
11e5db5de0ec5752dce736181a8d9d4c80a6f00f test(cli): add --color test (#1784)
99b78dc3ddeb94af33fe71942ec0312a9be3e2c2 chore(release): 3.3.1
```

**Comment by chaos-git** [comment]
> > Please run this test only on linux
> 
> You need add check `if (isLinux()) { /* HERE CODE OF TESTS */} ``

I see.. sure, I'll update.

**Comment by evilebottnawi** [comment]
Change commit name and do force push, thanks

**Comment by chaos-git** [comment]
> Change commit name and do force push, thanks

I realized when I saw the CLA comment. I've fixed the commit name now.

Let me know what you think about conditional-test.js

File: test/helpers/conditional-test.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+const isWindows = process.platform === 'win32';
+
+function skipSuiteOnWindows(reason) {
+  if (isWindows) {
+    test.skip(reason, () => {});
+  }
+  return isWindows;
+}
+
+module.exports.skipSuiteOnWindows = skipSuiteOnWindows;
```
Comment (evilebottnawi) [inline test/helpers/conditional-test.js]: let's rename this to `isWindows` for avoid misleading

Comment (chaos-git) [reply test/helpers/conditional-test.js]: This function does have the side effect of adding a skipped test which the name `isWindows()` would not really capture. [Jest uses the term `skipSuiteOnWindows`](https://github.com/facebook/jest/blob/master/packages/test-utils/src/ConditionalTest.ts#L30) but in this PR it's not skipping the suite, it's just skipping an individual test. What are your thoughts on `skipTestOnWindows()`?

I want to add that [I prefer Jest's way of doing this](https://github.com/facebook/jest/blob/master/packages/test-utils/src/ConditionalTest.ts#L30), but I'm not a javascript developer and I had issues getting it to work as expected. When I used `test.only(..)` the tests started failing because it wasn't shutting down the server properly. The only way I could fix it was by changing a larger portion of code than I wanted to. Perhaps you have more knowledge on how to make it so that we don't have to return a boolean, and can instead just have `skipSuiteOnWindows(..)` run `test.only(..)`.

Comment (evilebottnawi) [reply test/helpers/conditional-test.js]: :+1:

**Comment by chaos-git** [comment]
Taking a look..

**Comment by evilebottnawi** [comment]
Nodejs bug
