### PR TITLE
fix(options): allow passing promise function of webpack.config.js

### LINKED ISSUE #1946: Promise based webpack configs fail
- Operating System: OSX
- Node Version:v8.10.0 
- NPM Version: 5.6.0
- webpack Version:4.28.4
- webpack-dev-server Version:3.5.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
When using a promise based configuration the error responds with
```
TypeError: Cannot read property 'bonjour' of undefined
    at createConfig (node_modules/webpack-dev-server/lib/utils/createConfig.js:13:12)
    at processOptions (node_modules/webpack-dev-server/lib/utils/processOptions.js:22:19)

```

```js
// webpack.config.js
module.exports = new Promise(r=>setTimeout(r, 100, {}));
```

### Expected Behavior
When using a promise to launch webpack-dev-server the 

in 

```js
//processOptions.js 
function processOptions(config, argv, callback) {
  // processOptions {Promise}
  if (typeof config.then === 'function') {
///ERROR HERE -- argv is not passed ///
    config.then(processOptions).catch((err) => {
      // eslint-disable-next-line no-console
      console.error(err.stack || err);
      // eslint-disable-next-line no-process-exit
      process.exit();
    });

    return;
  }
```

### Actual Behavior
Should be something like

```js
function processOptions(config, argv, callback) {
  // processOptions {Promise}
  if (typeof config.then === 'function') {
///Fixed by passing argv.
    config.then( c =>processOptions(c, argv, callback)).catch((err) => {
      // eslint-disable-next-line no-console
      console.error(err.stack || err);
      // eslint-disable-next-line no-process-exit
      process.exit();
    });

    return;
  }
```

### For Bugs; How can we reproduce the behavior?
A solution is above.

### PR DESCRIPTION
**Pull request by hiroppy**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

yep

### Motivation / Use-Case

fixes #1946, #1945

### CODE REVIEW

File: test/helpers/test-bin.js [hunk 1]
```diff
@@ -36,13 +36,25 @@ function runWebackDevServer(testArgs, configPath) {
     child.on('error', (error) => reject(error));
 
     child.stdout.on('data', (data) => {
-      stdout += data.toString();
+      const str = data.toString();
+
+      stdout += str;
+
+      // if webpack.config.js is a promise function, it won't be able to call `close`
```
Comment (hiroppy) [inline test/helpers/test-bin.js]: I don't know why it couldn't call `close`, but I checked `examples/general/config-promise` and it works.

**Comment by hiroppy** [comment]
Master branch has the same errors about windows's CI.
https://github.com/webpack/webpack-dev-server/runs/139531630

I hope that these changes are not the cause. (anyway, we need to investigate it)

https://github.com/webpack/webpack-dev-server/pull/1947/checks?check_run_id=139790673

<details>

```
[error]PASS test/Server.test.js (26.733s)
[error]  ● Console
[error]..&#x2F;..&#x2F;..&#x2F;client&#x2F;socket.js] ‌.&#x2F;client&#x2F;socket.js‌ 1.05 KiB {‌main‌}‌ [built]‌
[error]    [..&#x2F;..&#x2F;..&#x2F;node_modules&#x2F;html-entities&#x2F;index.js] ‌.&#x2F;node_modules&#x2F;html-entities&#x2F;index.js‌ 231 bytes {‌main‌}‌ [built]‌
[error]http://localhost:8080/
[error]34mi‌ ‌｢wds｣‌: Content not from webpack is served from D:\a\1\s‌
[error]/1/s/node_modules/url/url.js 22.8 KiB {main} [built]
[error]PASS test/Entry.test.js
[error]PASS test/ContentBase.test.js
[error]PASS test/Proxy.test.js
[error](node:2920) ExperimentalWarning: The fs.promises API is experimental
[error]PASS test/options.test.js (39.114s)
[error]  ● Console
[error]PASS test/Client.test.js (22s)
[error]  ● Console
[error]PASS test/Validation.test.js
[error]PASS test/Hot.test.js
```
</details>

File: test/cli.test.js [hunk 2]
```diff
@@ -100,6 +100,22 @@ describe('CLI', () => {
...
+      false,
+      resolve(__dirname, 'fixtures/promise-config/webpack.config.js')
+    )
+      .then((output) => {
+        expect(output.code).toEqual(0);
+        done();
+      })
+      .catch((err) => {
+        // for windows
+        expect(err.stdout.includes('Compiled successfully.')).toEqual(true);
```
Comment (hiroppy) [inline test/cli.test.js]: windows 😠
