### PR TITLE
feat: improve host output and fix open

### LINKED ISSUE #2874: v4.0.0-beta.0 and host option
- Operating System: macOS 11.0.1
- Node Version: v14.15.1
- NPM Version: 6.14.8
- webpack Version: 5.8.0
- webpack-dev-server Version: 4.0.0-beta.0
- Browser: Chrome last

- [x] This is a **bug**
- [ ] This is a **modification** request

### Question

How should I replace the `host` option in the new version?
Perhaps I did not understand this from the changelog.

webpack-dev-server v3:

```js
devServer: {
  host: 'some.site.loc',
  <...>
}
```

with webpack-dev-server v4 I try:

```js
devServer: {
  client: {
    host: 'some.site.loc',
  }
  <...>
}
```

Result from console:

```
<i> [webpack-dev-server] Project is running at https://127.0.0.1:9090/
```

When I try open `https://some.site.loc:9090` I get response `Invalid Host header`.

If I do not change the option (I leave it as it was in the previous version), then by default `https://127.0.0.1:9090` will still open, but `https:/some.site.loc:9090` also works. In this case, I would like the console to write the correct address and the correct address to open in the browser.

### PR DESCRIPTION
**Pull request by alexander-akait**
- [x] This is a **bugfix**
- [x] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

fixes #2874

### Breaking Changes

No

### Additional Info

inspired by CRA

### CODE REVIEW

**Comment by alexander-akait** [comment]
When you use `0.0.0.0` or `::`, our output is:
```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Local: http://localhost:8081/
<i> [webpack-dev-server] On Your Network: http://192.168.0.5:8081/
```
When it is not IP:
```
<i> [webpack-dev-server] Project is running at http://local-dev.io:8081/
```

File: lib/Server.js [hunk 1]
```diff
@@ -580,17 +581,93 @@ class Server {
...
+    const prettyPrintUrl = (newHostname) =>
+      url.format({ protocol, hostname: newHostname, port, pathname: '/' });
+
+    let prettyHostname;
+    let lanUrlForTerminal;
+
+    if (hostname === '0.0.0.0' || hostname === '::') {
+      prettyHostname = 'localhost';
+
+      const localIP = internalIp.v4.sync();
```
Comment (ylemkimon) [inline lib/Server.js:597]:
```suggestion
      const localIP = hostname === '::' ? internalIp.v6.sync() : internalIp.v4.sync();
```

File: lib/Server.js [hunk 2]
```diff
@@ -580,17 +581,93 @@ class Server {
...
+
+      if (
+        /^10[.]|^172[.](1[6-9]|2[0-9]|3[0-1])[.]|^192[.]168[.]/.test(localIP)
+      ) {
+        // Address is private, format it for later use
```
Comment (ylemkimon) [inline lib/Server.js:602]: I think this check is not needed, as `0.0.0.0` (`::`) will bind to public address, if available.

File: test/cli/__snapshots__/cli.test.js.snap [hunk 3]
```diff
@@ -28,7 +28,7 @@ exports[`CLI --hot webpack 4 1`] = `
 `;
 
 exports[`CLI --hot webpack 5 1`] = `
```
Comment (ylemkimon) [inline test/cli/__snapshots__/cli.test.js.snap:30]: Note snapshots should be updated each for webpack 4 and 5.

File: lib/utils/createDomain.js [hunk 4]
```diff
@@ -8,27 +8,27 @@ function createDomain(options, server) {
   // use location hostname and port by default in createSocketUrl
```
Comment (ylemkimon) [inline lib/utils/createDomain.js:8]: `showStatus` now using its own logic, this is only used in client entries. I think this can be refactored in the future PR.

File: lib/Server.js (hunk 1 above)
Comment (alexander-akait) [reply lib/Server.js:597]: It is for terminal output, developer should copy past it from terminal, IPv6 is not supported in many browsers

File: lib/Server.js (hunk 2 above)
Comment (alexander-akait) [reply lib/Server.js:602]: You can have local public IP (it is very rare edge case, but it is possible), for example I can run it on my server with public IP

File: lib/utils/createDomain.js (hunk 4 above)
Comment (alexander-akait) [reply lib/utils/createDomain.js:8]: I think logic for terminal output and for entries is different, it is similar in some places, but it is for different purpose

File: lib/Server.js (hunk 2 above)
Comment (ylemkimon) [reply lib/Server.js:602]: In that case, I think the public IP should be printed.

Comment (alexander-akait) [reply lib/Server.js:602]: In this case we print two IP - local and network

File: lib/Server.js (hunk 1 above)
Comment (ylemkimon) [reply lib/Server.js:597]: `url` automatically formats IPv6 hostname with brackets, which most browsers support including IE 11, e.g., `http://[::]:8080`. I think IPv6 should take precendence over IPv4, if available.

File: lib/Server.js (hunk 2 above)
Comment (ylemkimon) [reply lib/Server.js:602]: IMHO, I see no reason not to print the internal IP (the IP address of the NIC) if it's public. It's still a network IP, but just not a LAN.

File: lib/Server.js (hunk 1 above)
Comment (alexander-akait) [reply lib/Server.js:597]: make sense, I hope this does not scare developers

File: lib/Server.js (hunk 2 above)
Comment (alexander-akait) [reply lib/Server.js:602]: I don't have strong opinion here, it was inspired by CRA and them feedback, but maybe you are right

Comment (alexander-akait) [reply lib/Server.js:602]: Let's simplify it, we will change it in future after feedback

**Comment by alexander-akait** [comment]
IPv6 is not supported by github actions, we can't test it :disappointed:

**Comment by alexander-akait** [comment]
https://github.com/actions/virtual-environments/issues/668#issuecomment-624080758

File: lib/Server.js [hunk 5]
```diff
@@ -580,17 +581,91 @@ class Server {
...
+      this.logger.info(
+        `Project is running at ${colors.info(useColor, localUrlForTerminal)}`
+      );
+    }
+
+    if (
+      this.options.dev &&
+      typeof this.options.dev.publicPath !== 'undefined'
+    ) {
+      this.options.info(
```
Comment (sprilukin) [inline lib/Server.js:625]: @alexander-akait looks like `this.options.info` should be replaced with `this.logger.info`

Comment (alexander-akait) [reply lib/Server.js:625]: Already fixed in master
