### PR TITLE
fixes #860: failure to exit on SIGINT race condition

### LINKED ISSUE #860: webpack-dev-server does not stop on Ctrl+C
Hi. I noticed that the latest version v2.4.2 have an issue around process signal handling. Pressing Ctrl+C to stop `webpack-dev-server` does not work **while compiling** assets. (NOTE: Ctrl+C works well after finished compilation.)

Also, I reverted the change of the PR #787 to workaround the issue for now.

OS: macOS 10.12.3
webpack-dev-server 2.4.2
webpack 2.3.2

### PR DESCRIPTION
**Pull request by shellscape**
**What kind of change does this PR introduce?**
Properly calls `process.exit` only after `server.close` has completed. Probable fix for reported edge case whereby the server process doesn't actually exit when SIGINT is sent.

**Did you add or update the `examples/`?**
No need

**Summary**
See above

**Does this PR introduce a breaking change?**
No

**Other information**
Added new test to confirm SIGINT detection works properly.

### CODE REVIEW

File: bin/webpack-dev-server.js [hunk 1]
```diff
@@ -390,8 +390,9 @@ function startDevServer(webpackOptions, options) {
 
   ['SIGINT', 'SIGTERM'].forEach((sig) => {
     process.on(sig, () => {
-      server.close();
-      process.exit(); // eslint-disable-line no-process-exit
+      server.close(() => {
```
Comment (michael-ciniawsky) [inline bin/webpack-dev-server.js]: `process.nextTick()` ? But not 💯

Comment (shellscape) [reply bin/webpack-dev-server.js]: @michael-ciniawsky hm? please elaborate :)

Comment (michael-ciniawsky) [reply bin/webpack-dev-server.js]: Hmm I think it is bananas from my side tbh :), the intend was 

```js
server.close()

process.nextTick(() => process.exit())
```

to ensure `server.close()` finishes before `process.exit()` is called by pushing it to the next EventLoop 'tick'.  But a callback to `server.close()` is definitely cleaner and more expressive/logical, so forget what I said 😛

Comment (shellscape) [reply bin/webpack-dev-server.js]: haha no worries. something good to keep in mind though!
