### PR TITLE
Replace socket.io with SockJS as discussed in #229

### LINKED ISSUE #195: Install Errors on node v0.12.4 (NPM 2.11.1)
I downloaded and installed Node and build a small project pulling in various modules
I was using gulp to do a very simple build but wanted to switch to WebPack

The WebPack module and various loader installed OK - and that gave me a CLI build but I wanted to have the near real time refresh of the dev server.

but when I tried to load the Dev Server

Installing with a simple 
npm install webpack-dev-server -save -D

Generated lots of RED Error lines in console.

Here is the relevant Error Section from Log

    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      bufferutil.cc
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C3861: 'ThrowException': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(218): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(218): error C3861: 'ThrowException': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(222): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(222): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(224): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(224): error C2660: 'v8::Integer::New' : function does not take 1 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(224): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(229): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(229): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(229): error C3861: 'ThrowException': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(229): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(233): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(233): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(233): error C3861: 'ThrowException': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(233): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(450): error C2660: 'v8::Object::New' : function does not take 0 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(451): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(451): error C3861: 'NewSymbol': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(457): error C2039: 'Dispose' : is not a member of 'v8::Persistent<T>' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              with
              [
                  T=v8::Object
              ]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(458): error C2039: 'Clear' : is not a member of 'v8::Persistent<T>' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              with
              [
                  T=v8::Object
              ]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(462): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(463): error C2228: left of '.As' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(463): error C2059: syntax error : ')' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(475): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(475): error C2228: left of '.As' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(475): error C2059: syntax error : ')' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(477): error C2039: 'GetCurrent' : is not a member of 'v8::Context' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(5212) : see declaration of 'v8::Context'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(477): error C2227: left of '->Global' must point to class/struct/union/generic type [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              type is ''unknown-type''
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(475): error C3861: 'NewSymbol': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(477): error C3861: 'GetCurrent': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(518): error C2146: syntax error : missing ';' before identifier 'request' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(518): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(490): error C2065: 'request' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(490): error C2228: left of '.data' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              type is ''unknown-type''
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(529): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(529): error C3861: 'NewSymbol': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(536): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(536): error C2228: left of '.As' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(536): error C2059: syntax error : ')' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(549): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(550): error C2466: cannot allocate an array of constant size 0 [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(550): error C2440: 'initializing' : cannot convert from 'int' to 'v8::Local<T>' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              with
              [
                  T=v8::Value
              ]
              No constructor could take the source type, or constructor overload resolution was ambiguous
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(549): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(555): error C2065: 'uv_work_t' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(555): error C2065: 'req' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(555): error C2448: 'NanAsyncExecute' : function-style initializer appears to be a function definition [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(560): error C2065: 'uv_work_t' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(560): error C2065: 'req' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(560): error C2448: 'NanAsyncExecuteComplete' : function-style initializer appears to be a function definition [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(570): error C2039: 'request' : is not a member of 'NanAsyncWorker' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(487) : see declaration of 'NanAsyncWorker'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(571): error C2065: 'NanAsyncExecute' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(571): error C2065: 'uv_after_work_cb' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(572): error C2146: syntax error : missing ')' before identifier 'NanAsyncExecuteComplete' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(572): error C2059: syntax error : ')' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(716): error C2661: 'v8::Local<T>::New' : no overloaded function takes 1 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              with
              [
                  T=v8::String
              ]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(769): error C2039: 'AsciiValue' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(769): error C2065: 'AsciiValue' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(769): error C2146: syntax error : missing ';' before identifier 'value' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(769): error C3861: 'value': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(817): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(829): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(832): error C2065: 'value' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(840): error C2065: 'value' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(840): error C2228: left of '.length' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              type is ''unknown-type''
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(858): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(873): error C2065: 'value' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(873): error C2228: left of '.length' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              type is ''unknown-type''
    ..\src\bufferutil.cc(27): error C2664: 'v8::FunctionTemplate::New' : cannot convert parameter 1 from 'void (__cdecl *)(const v8::FunctionCallbackInfo<T> &)' to 'v8::Isolate *' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              with
              [
                  T=v8::Value
              ]
              There is no context in which this conversion is possible
    ..\src\bufferutil.cc(32): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    ..\src\bufferutil.cc(32): error C3861: 'NewSymbol': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    ..\src\bufferutil.cc(60): error C2660: 'v8::True' : function does not take 0 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    ..\src\bufferutil.cc(81): error C2660: 'v8::True' : function does not take 0 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
    ..\src\bufferutil.cc(106): error C2660: 'v8::True' : function does not take 0 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
      validation.cc
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C3861: 'ThrowException': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(213): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(218): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(218): error C3861: 'ThrowException': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(222): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(222): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(224): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(224): error C2660: 'v8::Integer::New' : function does not take 1 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(224): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(229): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(229): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(229): error C3861: 'ThrowException': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(229): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(233): error C2039: 'ThrowException' : is not a member of 'v8' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(233): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(233): error C3861: 'ThrowException': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(233): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(450): error C2660: 'v8::Object::New' : function does not take 0 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(451): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(451): error C3861: 'NewSymbol': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(457): error C2039: 'Dispose' : is not a member of 'v8::Persistent<T>' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              with
              [
                  T=v8::Object
              ]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(458): error C2039: 'Clear' : is not a member of 'v8::Persistent<T>' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              with
              [
                  T=v8::Object
              ]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(462): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(463): error C2228: left of '.As' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(463): error C2059: syntax error : ')' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(475): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(475): error C2228: left of '.As' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(475): error C2059: syntax error : ')' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(477): error C2039: 'GetCurrent' : is not a member of 'v8::Context' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(5212) : see declaration of 'v8::Context'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(477): error C2227: left of '->Global' must point to class/struct/union/generic type [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              type is ''unknown-type''
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(475): error C3861: 'NewSymbol': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(477): error C3861: 'GetCurrent': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(518): error C2146: syntax error : missing ';' before identifier 'request' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(518): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(490): error C2065: 'request' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(490): error C2228: left of '.data' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              type is ''unknown-type''
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(529): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(529): error C3861: 'NewSymbol': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(536): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(536): error C2228: left of '.As' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(536): error C2059: syntax error : ')' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(549): error C2039: 'New' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(550): error C2466: cannot allocate an array of constant size 0 [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(550): error C2440: 'initializing' : cannot convert from 'int' to 'v8::Local<T>' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              with
              [
                  T=v8::Value
              ]
              No constructor could take the source type, or constructor overload resolution was ambiguous
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(549): error C3861: 'New': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(555): error C2065: 'uv_work_t' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(555): error C2065: 'req' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(555): error C2448: 'NanAsyncExecute' : function-style initializer appears to be a function definition [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(560): error C2065: 'uv_work_t' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(560): error C2065: 'req' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(560): error C2448: 'NanAsyncExecuteComplete' : function-style initializer appears to be a function definition [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(570): error C2039: 'request' : is not a member of 'NanAsyncWorker' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(487) : see declaration of 'NanAsyncWorker'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(571): error C2065: 'NanAsyncExecute' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(571): error C2065: 'uv_after_work_cb' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(572): error C2146: syntax error : missing ')' before identifier 'NanAsyncExecuteComplete' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(572): error C2059: syntax error : ')' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(716): error C2661: 'v8::Local<T>::New' : no overloaded function takes 1 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              with
              [
                  T=v8::String
              ]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(769): error C2039: 'AsciiValue' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(769): error C2065: 'AsciiValue' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(769): error C2146: syntax error : missing ';' before identifier 'value' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(769): error C3861: 'value': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(817): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(829): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(832): error C2065: 'value' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(840): error C2065: 'value' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(840): error C2228: left of '.length' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              type is ''unknown-type''
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(858): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(873): error C2065: 'value' : undeclared identifier [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\nan\nan.h(873): error C2228: left of '.length' must have class/struct/union [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              type is ''unknown-type''
    ..\src\validation.cc(108): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(816) : see declaration of 'v8::HandleScope::HandleScope'
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(800) : see declaration of 'v8::HandleScope'
    ..\src\validation.cc(109): error C2664: 'v8::FunctionTemplate::New' : cannot convert parameter 1 from 'void (__cdecl *)(const v8::FunctionCallbackInfo<T> &)' to 'v8::Isolate *' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              with
              [
                  T=v8::Value
              ]
              There is no context in which this conversion is possible

    ..\src\validation.cc(112): error C2039: 'NewSymbol' : is not a member of 'v8::String' [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
              C:\Users\steve\.node-gyp\0.12.4\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
    ..\src\validation.cc(112): error C3861: 'NewSymbol': identifier not found [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    ..\src\validation.cc(134): error C2660: 'v8::True' : function does not take 0 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
    ..\src\validation.cc(134): error C2660: 'v8::False' : function does not take 0 arguments [F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]

    webpack-dev-server@1.9.0 node_modules\webpack-dev-server
    ├── supports-color@1.3.1
    ├── connect-history-api-fallback@1.1.0
    ├── strip-ansi@2.0.1 (ansi-regex@1.1.1)
    ├── stream-cache@0.0.2
    ├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
    ├── webpack-dev-middleware@1.0.11 (memory-fs@0.1.1, enhanced-resolve@0.7.6)
    ├── serve-index@1.6.4 (escape-html@1.0.1, parseurl@1.3.0, batch@0.5.2, http-errors@1.3.1, debug@2.2.0, mime-types@2.0.14, accepts@1.2.9)
    ├── express@4.12.4 (merge-descriptors@1.0.0, cookie-signature@1.0.6, utils-merge@1.0.0, escape-html@1.0.1, methods@1.1.1, fresh@0.2.4, cookie@0.1.2, range-parser@1.0.2, finalhandler@0.3.6, content-type@1.0.1, vary@1.0.0, parseurl@1.3.0, serve-static@1.9.3, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.1, qs@2.4.2, on-finished@2.2.1, debug@2.2.0, send@0.12.3, etag@1.6.0, proxy-addr@1.0.8, accepts@1.2.9, type-is@1.6.3)
    ├── socket.io@1.3.5 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.1)
    └── socket.io-client@1.3.5 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, debug@0.7.4, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, socket.io-parser@2.2.4, engine.io-client@1.5.1)

And then when I try to run the project in the web server , I get some runtime errors with socket.io,

    Child server:
        Hash: 9b7801816eb0813306ab
        Version: webpack 1.9.10
        Time: 24685ms
        Asset    Size  Chunks             Chunk Names
        app.js  318 kB       0  [emitted]  
        main  [0] multi main 52 bytes {0} [built]
        + 82 hidden modules

    WARNING in (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/bufferutil in F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\lib
     @ (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js 8:19-57

    WARNING in (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/bufferutil in F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\lib
     @ (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/BufferUtil.js 10:19-57

    WARNING in (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/validation in F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\lib
     @ (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js 8:19-57

    WARNING in (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/validation in F:\Projects\ReactUpload\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\lib
     @ (webpack)-dev-server/~/socket.io-client/~/engine.io-client/~/ws/lib/Validation.js 10:19-57

    F:\Projects\ReactUpload\build\app.js:509
        var scriptElements = document.getElementsByTagName("script");
                                      ^
      ReferenceError: document is not defined

### LINKED ISSUE #229: webpack-dev-server will not work on Windows due to its dependency on node-gyp
Hi, I need to ask if webpack-dev-server's dependency on node-gyp is absolutely necessary?
node-gyp is a nightmare for many node developers that develop on a windows machine.
it needs a C++  compiler which forces you to download visual studio and all sorts of service packs that got nothing to do with node development. in our case - after a 1.6 Gigs of installations and dependencies we were still unable to make node-gyp work on windows...
Why would webpack-dev-server however need node-gyp as a dependency?
As far as I know it has an express http server with socket.io...   the webpack package alone doesn't require node-gyp, so why the webpack-dev-server need it?
Can you let it go? it creates a lot of unnecessary pain for developers...
Cheers
Ajar

### LINKED ISSUE #242: Error installing on iojs 3.0.0
Socket.io fails to build on the recently release iojs 3 (as per https://github.com/socketio/socket.io/issues/2213) which means webpack-dev-server fails to build as well. Leaving the issue here as a reference note, but nothing can be done about this until the upstream problem is resolved.

P.S. socket.io fails because of the ws dependency issue as tracked at https://github.com/websockets/ws/issues/549 which has been fixed with updated dependencies as per https://github.com/websockets/ws/commit/ee660710e151779a258f29f33040234c3133a63a and awaits publishing to npm. Once ws publishes, socket.io will bump it's dependency version, then webpack-dev-server should work on iojs 3

### LINKED ISSUE #258: webpack-dev-server fails to install in node 4 stable
here are the logs
```
npm http request GET https://registry.npmjs.org/webpack-dev-server
npm http 304 https://registry.npmjs.org/webpack-dev-server
npm WARN peerDependencies The peer dependency webpack@^1.3.0 included from webpack-dev-server will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm http request GET https://registry.npmjs.org/connect-history-api-fallback
npm http request GET https://registry.npmjs.org/optimist
npm http request GET https://registry.npmjs.org/serve-index
npm http request GET https://registry.npmjs.org/http-proxy
npm http request GET https://registry.npmjs.org/stream-cache
npm http request GET https://registry.npmjs.org/socket.io-client
npm http request GET https://registry.npmjs.org/socket.io
npm http request GET https://registry.npmjs.org/strip-ansi
npm http request GET https://registry.npmjs.org/webpack-dev-middleware
npm http request GET https://registry.npmjs.org/supports-color
npm http request GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/connect-history-api-fallback
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/socket.io-client
npm http 304 https://registry.npmjs.org/webpack-dev-middleware
npm http 304 https://registry.npmjs.org/stream-cache
npm http 304 https://registry.npmjs.org/http-proxy
npm http 200 https://registry.npmjs.org/socket.io
npm http 200 https://registry.npmjs.org/serve-index
npm http 200 https://registry.npmjs.org/express
npm WARN peerDependencies The peer dependency webpack@^1.0.0 included from webpack-dev-middleware will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm http request GET https://registry.npmjs.org/ansi-regex
npm http request GET https://registry.npmjs.org/memory-fs
npm http request GET https://registry.npmjs.org/mime
npm http request GET https://registry.npmjs.org/requires-port
npm http request GET https://registry.npmjs.org/socket.io-adapter
npm http request GET https://registry.npmjs.org/has-binary-data
npm http request GET https://registry.npmjs.org/eventemitter3
npm http request GET https://registry.npmjs.org/socket.io-parser
npm http request GET https://registry.npmjs.org/debug
npm http request GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/memory-fs
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/requires-port
npm http 304 https://registry.npmjs.org/socket.io-adapter
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/has-binary-data
npm http 304 https://registry.npmjs.org/socket.io-parser
npm http request GET https://registry.npmjs.org/array-flatten
npm http request GET https://registry.npmjs.org/minimist
npm http request GET https://registry.npmjs.org/content-type
npm http request GET https://registry.npmjs.org/engine.io
npm http request GET https://registry.npmjs.org/content-disposition
npm http request GET https://registry.npmjs.org/cookie-signature
npm http request GET https://registry.npmjs.org/cookie
npm http request GET https://registry.npmjs.org/accepts
npm http request GET https://registry.npmjs.org/escape-html
npm http request GET https://registry.npmjs.org/etag
npm http request GET https://registry.npmjs.org/fresh
npm http request GET https://registry.npmjs.org/depd
npm http request GET https://registry.npmjs.org/merge-descriptors
npm http request GET https://registry.npmjs.org/finalhandler
npm http request GET https://registry.npmjs.org/methods
npm http request GET https://registry.npmjs.org/indexof
npm http request GET https://registry.npmjs.org/parseuri
npm http request GET https://registry.npmjs.org/parseurl
npm http request GET https://registry.npmjs.org/on-finished
npm http request GET https://registry.npmjs.org/proxy-addr
npm http request GET https://registry.npmjs.org/backo2
npm http request GET https://registry.npmjs.org/to-array
npm http request GET https://registry.npmjs.org/range-parser
npm http request GET https://registry.npmjs.org/path-to-regexp
npm http request GET https://registry.npmjs.org/send
npm http request GET https://registry.npmjs.org/qs
npm http request GET https://registry.npmjs.org/utils-merge
npm http request GET https://registry.npmjs.org/type-is
npm http request GET https://registry.npmjs.org/component-bind
npm http request GET https://registry.npmjs.org/serve-static
npm http request GET https://registry.npmjs.org/object-component
npm http request GET https://registry.npmjs.org/has-binary
npm http request GET https://registry.npmjs.org/vary
npm http request GET https://registry.npmjs.org/component-emitter
npm http request GET https://registry.npmjs.org/engine.io-client
npm http 304 https://registry.npmjs.org/eventemitter3
npm http request GET https://registry.npmjs.org/batch
npm http 304 https://registry.npmjs.org/wordwrap
npm http request GET https://registry.npmjs.org/http-errors
npm http request GET https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/merge-descriptors
npm http 304 https://registry.npmjs.org/content-type
npm http 304 https://registry.npmjs.org/cookie
npm http 304 https://registry.npmjs.org/fresh
npm http 304 https://registry.npmjs.org/proxy-addr
npm http 304 https://registry.npmjs.org/backo2
npm http 304 https://registry.npmjs.org/type-is
npm http 304 https://registry.npmjs.org/on-finished
npm http 304 https://registry.npmjs.org/to-array
npm http 304 https://registry.npmjs.org/escape-html
npm http 304 https://registry.npmjs.org/array-flatten
npm http 304 https://registry.npmjs.org/etag
npm http 304 https://registry.npmjs.org/content-disposition
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/parseuri
npm http 304 https://registry.npmjs.org/component-emitter
npm http 304 https://registry.npmjs.org/has-binary
npm http 304 https://registry.npmjs.org/send
npm http 304 https://registry.npmjs.org/utils-merge
npm http 304 https://registry.npmjs.org/vary
npm http 304 https://registry.npmjs.org/object-component
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/engine.io
npm http 304 https://registry.npmjs.org/depd
npm http 304 https://registry.npmjs.org/engine.io-client
npm http 304 https://registry.npmjs.org/cookie-signature
npm http 304 https://registry.npmjs.org/component-bind
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/indexof
npm http 304 https://registry.npmjs.org/path-to-regexp
npm http 200 https://registry.npmjs.org/accepts
npm http fetch GET https://registry.npmjs.org/accepts/-/accepts-1.2.13.tgz
npm http 304 https://registry.npmjs.org/batch
npm http 304 https://registry.npmjs.org/http-errors
npm http request GET https://registry.npmjs.org/better-assert
npm http 200 https://registry.npmjs.org/qs
npm http fetch GET https://registry.npmjs.org/qs/-/qs-4.0.0.tgz
npm http 304 https://registry.npmjs.org/finalhandler
npm http request GET https://registry.npmjs.org/object-keys
npm http request GET https://registry.npmjs.org/ms
npm http request GET https://registry.npmjs.org/isarray
npm http 200 https://registry.npmjs.org/mime-types
npm http request GET https://registry.npmjs.org/base64id
npm http fetch 200 https://registry.npmjs.org/accepts/-/accepts-1.2.13.tgz
npm http request GET https://registry.npmjs.org/has-cors
npm http request GET https://registry.npmjs.org/parsejson
npm http request GET https://registry.npmjs.org/parseqs
npm http request GET https://registry.npmjs.org/component-inherit
npm http fetch GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http request GET https://registry.npmjs.org/engine.io-parser
npm http request GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/better-assert
npm http 304 https://registry.npmjs.org/object-keys
npm http request GET https://registry.npmjs.org/statuses
npm http 304 https://registry.npmjs.org/isarray
npm http request GET https://registry.npmjs.org/mime-db
npm http request GET https://registry.npmjs.org/ws
npm http fetch 200 https://registry.npmjs.org/qs/-/qs-4.0.0.tgz
npm http 304 https://registry.npmjs.org/base64id
npm http 200 https://registry.npmjs.org/serve-static
npm http 304 https://registry.npmjs.org/ms
npm http 304 https://registry.npmjs.org/has-cors
npm http 304 https://registry.npmjs.org/parsejson
npm http request GET https://registry.npmjs.org/negotiator
npm http 304 https://registry.npmjs.org/component-inherit
npm http 304 https://registry.npmjs.org/parseqs
npm http request GET https://registry.npmjs.org/callsite
npm http 304 https://registry.npmjs.org/engine.io-parser
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/statuses
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/mime-db
npm http request GET https://registry.npmjs.org/json3
npm http 304 https://registry.npmjs.org/negotiator
npm http request GET https://registry.npmjs.org/benchmark
npm http request GET https://registry.npmjs.org/webpack
npm http request GET https://registry.npmjs.org/unpipe
npm http 304 https://registry.npmjs.org/callsite
npm http request GET https://registry.npmjs.org/forwarded
npm http request GET https://registry.npmjs.org/ee-first
npm http request GET https://registry.npmjs.org/media-typer
npm http request GET https://registry.npmjs.org/ipaddr.js
npm http request GET https://registry.npmjs.org/destroy
npm http 304 https://registry.npmjs.org/json3
npm http 200 https://registry.npmjs.org/benchmark
npm http fetch GET https://registry.npmjs.org/benchmark/-/benchmark-1.0.0.tgz
npm http fetch 200 https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http request GET https://registry.npmjs.org/base64-arraybuffer
npm http request GET https://registry.npmjs.org/blob
npm http 304 https://registry.npmjs.org/forwarded
npm http 304 https://registry.npmjs.org/unpipe
npm http request GET https://registry.npmjs.org/arraybuffer.slice
npm http request GET https://registry.npmjs.org/utf8
npm http request GET https://registry.npmjs.org/after
npm http 304 https://registry.npmjs.org/ee-first
npm http 304 https://registry.npmjs.org/media-typer
npm http request GET https://registry.npmjs.org/bufferutil
npm http request GET https://registry.npmjs.org/utf-8-validate
npm http request GET https://registry.npmjs.org/options
npm http request GET https://registry.npmjs.org/ultron
npm http 304 https://registry.npmjs.org/destroy
npm http fetch 200 https://registry.npmjs.org/benchmark/-/benchmark-1.0.0.tgz
npm http 304 https://registry.npmjs.org/arraybuffer.slice
npm http 304 https://registry.npmjs.org/utf8
npm http 304 https://registry.npmjs.org/blob
npm http 304 https://registry.npmjs.org/base64-arraybuffer
npm http fetch GET https://github.com/component/global/archive/v2.0.1.tar.gz
npm http 304 https://registry.npmjs.org/after
npm http 304 https://registry.npmjs.org/ipaddr.js
npm http 304 https://registry.npmjs.org/utf-8-validate
npm http 304 https://registry.npmjs.org/ultron
npm http 304 https://registry.npmjs.org/bufferutil
npm http 304 https://registry.npmjs.org/options
npm http request GET https://registry.npmjs.org/bindings
npm http fetch 200 https://github.com/component/global/archive/v2.0.1.tar.gz
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/webpack
npm http 200 https://registry.npmjs.org/nan
npm http request GET https://registry.npmjs.org/enhanced-resolve
npm http request GET https://registry.npmjs.org/esprima
npm http request GET https://registry.npmjs.org/clone
npm http request GET https://registry.npmjs.org/node-libs-browser
npm http request GET https://registry.npmjs.org/mkdirp
npm http request GET https://registry.npmjs.org/interpret
npm http request GET https://registry.npmjs.org/async
npm http request GET https://registry.npmjs.org/watchpack
npm http request GET https://registry.npmjs.org/tapable
npm http request GET https://registry.npmjs.org/webpack-core
npm http request GET https://registry.npmjs.org/uglify-js

> bufferutil@1.1.0 install /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp http GET https://nodejs.org/dist/v4.0.0/node-v4.0.0-headers.tar.gz
gyp http 200 https://nodejs.org/dist/v4.0.0/node-v4.0.0-headers.tar.gz
gyp http GET https://nodejs.org/dist/v4.0.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v4.0.0/SHASUMS256.txt
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion
      from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument
      ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local'
      against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
      'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/bufferutil.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/patrick/.nvm/versions/node/v4.0.0/bin/node" "/Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/tapable
npm http 304 https://registry.npmjs.org/interpret
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/webpack-core
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/node-libs-browser
npm http 304 https://registry.npmjs.org/watchpack
npm http 304 https://registry.npmjs.org/enhanced-resolve
npm http 200 https://registry.npmjs.org/async
npm http request GET https://registry.npmjs.org/has-flag
npm http 304 https://registry.npmjs.org/has-flag
npm http request GET https://registry.npmjs.org/constants-browserify
npm http request GET https://registry.npmjs.org/console-browserify
npm http request GET https://registry.npmjs.org/domain-browser
npm http request GET https://registry.npmjs.org/events
npm http request GET https://registry.npmjs.org/https-browserify
npm http request GET https://registry.npmjs.org/os-browserify
npm http request GET https://registry.npmjs.org/path-browserify
npm http request GET https://registry.npmjs.org/process
npm http request GET https://registry.npmjs.org/http-browserify
npm http request GET https://registry.npmjs.org/crypto-browserify
npm http request GET https://registry.npmjs.org/querystring-es3
npm http request GET https://registry.npmjs.org/buffer
npm http request GET https://registry.npmjs.org/string_decoder
npm http request GET https://registry.npmjs.org/stream-browserify
npm http request GET https://registry.npmjs.org/tty-browserify
npm http request GET https://registry.npmjs.org/punycode
npm http request GET https://registry.npmjs.org/util
npm http request GET https://registry.npmjs.org/url
npm http request GET https://registry.npmjs.org/timers-browserify
npm http request GET https://registry.npmjs.org/vm-browserify
npm http request GET https://registry.npmjs.org/browserify-zlib
npm http request GET https://registry.npmjs.org/assert
npm http request GET https://registry.npmjs.org/readable-stream
npm http request GET https://registry.npmjs.org/source-list-map
npm http request GET https://registry.npmjs.org/graceful-fs
npm http request GET https://registry.npmjs.org/chokidar
npm http 304 https://registry.npmjs.org/https-browserify
npm http 304 https://registry.npmjs.org/domain-browser
npm http 304 https://registry.npmjs.org/events
npm http request GET https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/console-browserify
npm http 304 https://registry.npmjs.org/process
npm http 304 https://registry.npmjs.org/tty-browserify
npm http 304 https://registry.npmjs.org/vm-browserify
npm http 304 https://registry.npmjs.org/timers-browserify
npm http request GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/querystring-es3
npm http 304 https://registry.npmjs.org/os-browserify
npm http 304 https://registry.npmjs.org/path-browserify
npm http 304 https://registry.npmjs.org/constants-browserify
npm http 304 https://registry.npmjs.org/http-browserify
npm http 304 https://registry.npmjs.org/browserify-zlib
npm http 304 https://registry.npmjs.org/crypto-browserify
npm http 200 https://registry.npmjs.org/url
npm http 304 https://registry.npmjs.org/assert
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/util
npm http 304 https://registry.npmjs.org/stream-browserify
npm http 304 https://registry.npmjs.org/graceful-fs
npm http request GET https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/source-list-map
npm http 304 https://registry.npmjs.org/chokidar
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/buffer
npm http request GET https://registry.npmjs.org/arrify
npm http request GET https://registry.npmjs.org/async-each
npm http request GET https://registry.npmjs.org/glob-parent
npm http request GET https://registry.npmjs.org/anymatch
npm http request GET https://registry.npmjs.org/path-is-absolute
npm http request GET https://registry.npmjs.org/is-binary-path
npm http request GET https://registry.npmjs.org/is-glob
npm http request GET https://registry.npmjs.org/fsevents
npm http request GET https://registry.npmjs.org/readdirp
npm http 304 https://registry.npmjs.org/arrify
npm http 304 https://registry.npmjs.org/anymatch
npm http 304 https://registry.npmjs.org/async-each
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/glob-parent
npm http 304 https://registry.npmjs.org/is-binary-path
npm http 304 https://registry.npmjs.org/is-glob
npm http 304 https://registry.npmjs.org/fsevents
npm http request GET https://registry.npmjs.org/date-now
npm http request GET https://registry.npmjs.org/querystring
npm http 304 https://registry.npmjs.org/readdirp
npm http request GET https://registry.npmjs.org/Base64
npm http 200 https://registry.npmjs.org/yargs
npm http request GET https://registry.npmjs.org/core-util-is
npm http request GET https://registry.npmjs.org/binary-extensions
npm http 304 https://registry.npmjs.org/date-now
npm http request GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/Base64
npm http 304 https://registry.npmjs.org/querystring
npm http 304 https://registry.npmjs.org/core-util-is
npm http request GET https://registry.npmjs.org/pako
npm http request GET https://registry.npmjs.org/base64-js
npm http request GET https://registry.npmjs.org/is-array
npm http request GET https://registry.npmjs.org/ieee754
npm http request GET https://registry.npmjs.org/micromatch
npm http 304 https://registry.npmjs.org/binary-extensions
npm http request GET https://registry.npmjs.org/decamelize
npm http request GET https://registry.npmjs.org/window-size
npm http request GET https://registry.npmjs.org/camelcase
npm http request GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/pako
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/base64-js
npm http 304 https://registry.npmjs.org/is-array
npm http 304 https://registry.npmjs.org/ieee754
npm http 304 https://registry.npmjs.org/window-size
npm http 304 https://registry.npmjs.org/decamelize
npm http request GET https://registry.npmjs.org/pbkdf2-compat
npm http request GET https://registry.npmjs.org/ripemd160
npm http request GET https://registry.npmjs.org/sha.js
npm http 304 https://registry.npmjs.org/micromatch
npm http request GET https://registry.npmjs.org/array-unique
npm http request GET https://registry.npmjs.org/expand-brackets
npm http request GET https://registry.npmjs.org/extglob
npm http request GET https://registry.npmjs.org/arr-diff
npm http request GET https://registry.npmjs.org/filename-regex
npm http request GET https://registry.npmjs.org/object.omit
npm http request GET https://registry.npmjs.org/regex-cache
npm http request GET https://registry.npmjs.org/kind-of
npm http request GET https://registry.npmjs.org/braces
npm http request GET https://registry.npmjs.org/parse-glob
npm http 304 https://registry.npmjs.org/sha.js
npm http 304 https://registry.npmjs.org/pbkdf2-compat
npm http 304 https://registry.npmjs.org/ripemd160
npm http 304 https://registry.npmjs.org/minimatch
npm http request GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/braces
npm http 304 https://registry.npmjs.org/parse-glob
npm http request GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/filename-regex
npm http 304 https://registry.npmjs.org/object.omit
npm http 304 https://registry.npmjs.org/kind-of
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/extglob
npm http 304 https://registry.npmjs.org/array-unique
npm http 304 https://registry.npmjs.org/regex-cache
npm http 304 https://registry.npmjs.org/expand-brackets
npm http 304 https://registry.npmjs.org/arr-diff
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http request GET https://registry.npmjs.org/for-own
npm http request GET https://registry.npmjs.org/array-slice
npm http request GET https://registry.npmjs.org/isobject
npm http request GET https://registry.npmjs.org/success-symbol
npm http request GET https://registry.npmjs.org/ansi-green
npm http request GET https://registry.npmjs.org/arr-flatten
npm http request GET https://registry.npmjs.org/is-extglob
npm http request GET https://registry.npmjs.org/is-primitive
npm http request GET https://registry.npmjs.org/is-dotfile
npm http request GET https://registry.npmjs.org/is-equal-shallow
npm http request GET https://registry.npmjs.org/glob-base
npm http request GET https://registry.npmjs.org/repeat-element
npm http request GET https://registry.npmjs.org/preserve
npm http request GET https://registry.npmjs.org/lazy-cache
npm http request GET https://registry.npmjs.org/expand-range
npm http 304 https://registry.npmjs.org/array-slice
npm http 304 https://registry.npmjs.org/arr-flatten
npm http 304 https://registry.npmjs.org/is-extglob
npm http 304 https://registry.npmjs.org/is-equal-shallow
npm http 304 https://registry.npmjs.org/ansi-green
npm http 304 https://registry.npmjs.org/for-own
npm http 304 https://registry.npmjs.org/success-symbol
npm http 304 https://registry.npmjs.org/lazy-cache
npm http 304 https://registry.npmjs.org/preserve
npm http 304 https://registry.npmjs.org/isobject
npm http 304 https://registry.npmjs.org/is-primitive
npm http 304 https://registry.npmjs.org/is-dotfile
npm http 304 https://registry.npmjs.org/glob-base
npm http request GET https://registry.npmjs.org/ansi-wrap
npm http request GET https://registry.npmjs.org/for-in
npm http 304 https://registry.npmjs.org/expand-range
npm http 304 https://registry.npmjs.org/repeat-element
npm http request GET https://registry.npmjs.org/fill-range
npm http 304 https://registry.npmjs.org/for-in
npm http 304 https://registry.npmjs.org/ansi-wrap
npm http 304 https://registry.npmjs.org/fill-range
npm http request GET https://registry.npmjs.org/randomatic
npm http request GET https://registry.npmjs.org/is-number
npm http request GET https://registry.npmjs.org/repeat-string
npm http 304 https://registry.npmjs.org/is-number
npm http 304 https://registry.npmjs.org/randomatic
npm http 304 https://registry.npmjs.org/repeat-string

> utf-8-validate@1.1.0 install /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion
      from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument
      ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local'
      against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
      'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/validation.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/patrick/.nvm/versions/node/v4.0.0/bin/node" "/Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0

> utf-8-validate@1.1.0 install /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion
      from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument
      ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local'
      against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
      'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/validation.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/patrick/.nvm/versions/node/v4.0.0/bin/node" "/Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> bufferutil@1.1.0 install /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion
      from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument
      ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/patrick/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local'
      against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
      'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/bufferutil.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/patrick/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/patrick/.nvm/versions/node/v4.0.0/bin/node" "/Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> fsevents@0.3.8 install /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm WARN optional dep failed, continuing bufferutil@1.1.0
/Users/patrick/.nvm/versions/node/v4.0.0/bin/webpack-dev-server -> /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm http request GET https://registry.npmjs.org/webpack
npm http 304 https://registry.npmjs.org/webpack
npm http request GET https://registry.npmjs.org/async
npm http request GET https://registry.npmjs.org/enhanced-resolve
npm http request GET https://registry.npmjs.org/memory-fs
npm http request GET https://registry.npmjs.org/interpret
npm http request GET https://registry.npmjs.org/node-libs-browser
npm http request GET https://registry.npmjs.org/supports-color
npm http request GET https://registry.npmjs.org/esprima
npm http request GET https://registry.npmjs.org/mkdirp
npm http request GET https://registry.npmjs.org/clone
npm http request GET https://registry.npmjs.org/tapable
npm http request GET https://registry.npmjs.org/watchpack
npm http request GET https://registry.npmjs.org/webpack-core
npm http request GET https://registry.npmjs.org/optimist
npm http request GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/memory-fs
npm http 304 https://registry.npmjs.org/interpret
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/enhanced-resolve
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/watchpack
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/webpack-core
npm http 304 https://registry.npmjs.org/tapable
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/node-libs-browser
npm http request GET https://registry.npmjs.org/has-flag
npm http request GET https://registry.npmjs.org/constants-browserify
npm http request GET https://registry.npmjs.org/console-browserify
npm http request GET https://registry.npmjs.org/events
npm http request GET https://registry.npmjs.org/domain-browser
npm http request GET https://registry.npmjs.org/https-browserify
npm http request GET https://registry.npmjs.org/os-browserify
npm http request GET https://registry.npmjs.org/path-browserify
npm http request GET https://registry.npmjs.org/process
npm http request GET https://registry.npmjs.org/buffer
npm http request GET https://registry.npmjs.org/http-browserify
npm http request GET https://registry.npmjs.org/readable-stream
npm http request GET https://registry.npmjs.org/querystring-es3
npm http request GET https://registry.npmjs.org/string_decoder
npm http request GET https://registry.npmjs.org/stream-browserify
npm http request GET https://registry.npmjs.org/tty-browserify
npm http request GET https://registry.npmjs.org/timers-browserify
npm http request GET https://registry.npmjs.org/punycode
npm http request GET https://registry.npmjs.org/util
npm http request GET https://registry.npmjs.org/url
npm http request GET https://registry.npmjs.org/vm-browserify
npm http request GET https://registry.npmjs.org/browserify-zlib
npm http request GET https://registry.npmjs.org/assert
npm http request GET https://registry.npmjs.org/crypto-browserify
npm http request GET https://registry.npmjs.org/graceful-fs
npm http request GET https://registry.npmjs.org/minimist
npm http request GET https://registry.npmjs.org/source-list-map
npm http request GET https://registry.npmjs.org/chokidar
npm http request GET https://registry.npmjs.org/wordwrap
npm http request GET https://registry.npmjs.org/source-map
npm http request GET https://registry.npmjs.org/uglify-to-browserify
npm http request GET https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/https-browserify
npm http 304 https://registry.npmjs.org/process
npm http 304 https://registry.npmjs.org/http-browserify
npm http 304 https://registry.npmjs.org/buffer
npm http 304 https://registry.npmjs.org/timers-browserify
npm http 304 https://registry.npmjs.org/assert
npm http 304 https://registry.npmjs.org/stream-browserify
npm http 304 https://registry.npmjs.org/tty-browserify
npm http 304 https://registry.npmjs.org/url
npm http 304 https://registry.npmjs.org/constants-browserify
npm http 304 https://registry.npmjs.org/console-browserify
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/source-list-map
npm http 304 https://registry.npmjs.org/chokidar
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/vm-browserify
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/browserify-zlib
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/graceful-fs
npm http request GET https://registry.npmjs.org/arrify
npm http request GET https://registry.npmjs.org/async-each
npm http request GET https://registry.npmjs.org/anymatch
npm http request GET https://registry.npmjs.org/glob-parent
npm http request GET https://registry.npmjs.org/is-binary-path
npm http request GET https://registry.npmjs.org/path-is-absolute
npm http request GET https://registry.npmjs.org/is-glob
npm http request GET https://registry.npmjs.org/fsevents
npm http request GET https://registry.npmjs.org/readdirp
npm http 304 https://registry.npmjs.org/yargs
npm http request GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/has-flag
npm http 304 https://registry.npmjs.org/os-browserify
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/events
npm http 304 https://registry.npmjs.org/path-browserify
npm http 304 https://registry.npmjs.org/domain-browser
npm http 304 https://registry.npmjs.org/util
npm http 304 https://registry.npmjs.org/crypto-browserify
npm http 304 https://registry.npmjs.org/querystring-es3
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm http 304 https://registry.npmjs.org/async-each
npm http 304 https://registry.npmjs.org/readdirp
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http request GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/is-glob
npm http 304 https://registry.npmjs.org/glob-parent
npm http 304 https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/amdefine
npm http request GET https://registry.npmjs.org/date-now
npm http request GET https://registry.npmjs.org/indexof
npm http request GET https://registry.npmjs.org/querystring
npm http request GET https://registry.npmjs.org/Base64
npm http request GET https://registry.npmjs.org/core-util-is
npm http request GET https://registry.npmjs.org/isarray
npm http request GET https://registry.npmjs.org/decamelize
npm http request GET https://registry.npmjs.org/window-size
npm http request GET https://registry.npmjs.org/camelcase
npm http request GET https://registry.npmjs.org/pako
npm http request GET https://registry.npmjs.org/is-array
npm http request GET https://registry.npmjs.org/base64-js
npm http request GET https://registry.npmjs.org/ieee754
npm http 304 https://registry.npmjs.org/arrify
npm http request GET https://registry.npmjs.org/ripemd160
npm http request GET https://registry.npmjs.org/pbkdf2-compat
npm http request GET https://registry.npmjs.org/sha.js
npm http 304 https://registry.npmjs.org/is-binary-path
npm http 304 https://registry.npmjs.org/anymatch
npm http 304 https://registry.npmjs.org/inherits
npm http request GET https://registry.npmjs.org/binary-extensions
npm http 304 https://registry.npmjs.org/date-now
npm http 304 https://registry.npmjs.org/querystring
npm http request GET https://registry.npmjs.org/micromatch
npm http 304 https://registry.npmjs.org/indexof
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/decamelize
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/ieee754
npm http request GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/isarray
npm http 304 https://registry.npmjs.org/is-array
npm http 304 https://registry.npmjs.org/base64-js
npm http 304 https://registry.npmjs.org/ripemd160
npm http 304 https://registry.npmjs.org/pbkdf2-compat
npm http 304 https://registry.npmjs.org/sha.js
npm http 304 https://registry.npmjs.org/window-size
npm http 304 https://registry.npmjs.org/Base64
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/pako
npm http 304 https://registry.npmjs.org/minimatch
npm http request GET https://registry.npmjs.org/sigmund
npm http request GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/binary-extensions

> fsevents@0.3.8 install /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm http 304 https://registry.npmjs.org/micromatch
npm http request GET https://registry.npmjs.org/array-unique
npm http request GET https://registry.npmjs.org/arr-diff
npm http request GET https://registry.npmjs.org/expand-brackets
npm http request GET https://registry.npmjs.org/braces
npm http request GET https://registry.npmjs.org/filename-regex
npm http request GET https://registry.npmjs.org/object.omit
npm http request GET https://registry.npmjs.org/extglob
npm http request GET https://registry.npmjs.org/kind-of
npm http request GET https://registry.npmjs.org/regex-cache
npm http request GET https://registry.npmjs.org/parse-glob
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/expand-brackets
npm http 304 https://registry.npmjs.org/arr-diff
npm http 304 https://registry.npmjs.org/extglob
npm http 304 https://registry.npmjs.org/parse-glob
npm http 304 https://registry.npmjs.org/kind-of
npm http 304 https://registry.npmjs.org/regex-cache
npm http 304 https://registry.npmjs.org/array-unique
npm http 304 https://registry.npmjs.org/object.omit
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/braces
npm http 304 https://registry.npmjs.org/filename-regex
npm http request GET https://registry.npmjs.org/isobject
npm http request GET https://registry.npmjs.org/arr-flatten
npm http request GET https://registry.npmjs.org/array-slice
npm http request GET https://registry.npmjs.org/for-own
npm http request GET https://registry.npmjs.org/is-extglob
npm http request GET https://registry.npmjs.org/ansi-green
npm http request GET https://registry.npmjs.org/is-primitive
npm http request GET https://registry.npmjs.org/success-symbol
npm http request GET https://registry.npmjs.org/is-equal-shallow
npm http request GET https://registry.npmjs.org/is-dotfile
npm http request GET https://registry.npmjs.org/glob-base
npm http request GET https://registry.npmjs.org/preserve
npm http request GET https://registry.npmjs.org/repeat-element
npm http request GET https://registry.npmjs.org/lazy-cache
npm http request GET https://registry.npmjs.org/expand-range
npm http 304 https://registry.npmjs.org/array-slice
npm http 304 https://registry.npmjs.org/arr-flatten
npm http 304 https://registry.npmjs.org/preserve
npm http 304 https://registry.npmjs.org/success-symbol
npm http 304 https://registry.npmjs.org/isobject
npm http 304 https://registry.npmjs.org/is-primitive
npm http 304 https://registry.npmjs.org/for-own
npm http 304 https://registry.npmjs.org/is-extglob
npm http 304 https://registry.npmjs.org/ansi-green
npm http 304 https://registry.npmjs.org/is-dotfile
npm http 304 https://registry.npmjs.org/glob-base
npm http 304 https://registry.npmjs.org/is-equal-shallow
npm http 304 https://registry.npmjs.org/repeat-element
npm http 304 https://registry.npmjs.org/expand-range
npm http request GET https://registry.npmjs.org/for-in
npm http request GET https://registry.npmjs.org/ansi-wrap
npm http 304 https://registry.npmjs.org/lazy-cache
npm http request GET https://registry.npmjs.org/fill-range
npm http 304 https://registry.npmjs.org/for-in
npm http 304 https://registry.npmjs.org/ansi-wrap
npm http 304 https://registry.npmjs.org/fill-range
npm http request GET https://registry.npmjs.org/randomatic
npm http request GET https://registry.npmjs.org/is-number
npm http request GET https://registry.npmjs.org/repeat-string
npm http 304 https://registry.npmjs.org/randomatic
npm http 304 https://registry.npmjs.org/is-number
npm http 304 https://registry.npmjs.org/repeat-string
/Users/patrick/.nvm/versions/node/v4.0.0/bin/webpack -> /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack/bin/webpack.js
webpack@1.12.1 /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack
├── interpret@0.6.5
├── tapable@0.1.9
├── async@1.4.2
├── memory-fs@0.2.0
├── clone@1.0.2
├── esprima@2.6.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── enhanced-resolve@0.9.0 (graceful-fs@3.0.8)
├── supports-color@3.1.1 (has-flag@1.0.0)
├── webpack-core@0.6.6 (source-list-map@0.1.5, source-map@0.4.4)
├── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.1.34, yargs@3.5.4)
├── node-libs-browser@0.5.2 (https-browserify@0.0.0, tty-browserify@0.0.0, constants-browserify@0.0.1, path-browserify@0.0.0, os-browserify@0.1.2, process@0.11.1, string_decoder@0.10.31, punycode@1.3.2, domain-browser@1.1.4, querystring-es3@0.2.1, assert@1.3.0, timers-browserify@1.4.1, events@1.0.2, stream-browserify@1.0.0, util@0.10.3, console-browserify@1.1.0, vm-browserify@0.0.4, url@0.10.3, readable-stream@1.1.13, buffer@3.4.3, http-browserify@1.7.0, browserify-zlib@0.1.4, crypto-browserify@3.2.8)
└── watchpack@0.2.8 (graceful-fs@3.0.8, async@0.9.2, chokidar@1.0.5)

webpack-dev-server@1.10.1 /Users/patrick/.nvm/versions/node/v4.0.0/lib/node_modules/webpack-dev-server
├── supports-color@1.3.1
├── connect-history-api-fallback@1.1.0
├── stream-cache@0.0.2
├── strip-ansi@2.0.1 (ansi-regex@1.1.1)
├── http-proxy@1.11.2 (requires-port@0.0.1, eventemitter3@1.1.1)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── serve-index@1.7.2 (escape-html@1.0.2, parseurl@1.3.0, batch@0.5.2, debug@2.2.0, http-errors@1.3.1, accepts@1.2.13, mime-types@2.1.6)
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, path-to-regexp@0.1.7, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, qs@4.0.0, debug@2.2.0, finalhandler@0.4.0, on-finished@2.3.0, accepts@1.2.13, send@0.13.0, type-is@1.6.8, proxy-addr@1.0.8)
├── socket.io-client@1.3.6 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, debug@0.7.4, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, socket.io-parser@2.2.4, engine.io-client@1.5.2)
├── socket.io@1.3.6 (has-binary-data@0.1.3, debug@2.1.0, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.2)
├── webpack@1.12.1 (interpret@0.6.5, tapable@0.1.9, memory-fs@0.2.0, clone@1.0.2, async@1.4.2, supports-color@3.1.1, esprima@2.6.0, mkdirp@0.5.1, enhanced-resolve@0.9.0, webpack-core@0.6.6, uglify-js@2.4.24, node-libs-browser@0.5.2, watchpack@0.2.8)
└── webpack-dev-middleware@1.2.0 (memory-fs@0.2.0, mime@1.3.4)
```

also has an error `Segmentation fault: 11`

### LINKED ISSUE #267: Error installing on iojs 4.0.0
## Error 1

```
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pmq20/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
```

## Error 2

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pmq20/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.1.0
```

## Error 3

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pmq20/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
```

## Error 4 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pmq20/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.2
gyp ERR! not ok 
```

### PR DESCRIPTION
**Pull request by SpaceK33z**
The socket.io dependency causes node-gyp to be used. This results in a lot of issues with Windows and Linux installs. SockJS is much, much lighter and is node-only. This also results in a 5mb package size decrease :).

This is a relatively big change, so it would be best if some people test this in their project.

Fixes #229, #276, fixes #195, fixes #267, fixes #258 and fixes #242

### CODE REVIEW

File: client/live.js [hunk 1]
```diff
@@ -1,8 +1,40 @@
...
+	sock = new SockJS('/sockjs-node');
+
+	clearInterval(recInterval);
+
+	sock.onclose = function() {
+		handlers.close();
+
+		// Try to reconnect.
+		sock = null;
+		recInterval = setInterval(function () {
```
Comment (Lekensteyn) [inline client/live.js]: Since you are clearing the interval immediately on execution, why not just:

    recTimeout = setTimeout(newConnection, 2000, handlers);

Since newConnection is only called once, the clearInterval is not needed. Same for the other thing in live.js.

Comment (SpaceK33z) [inline client/live.js]: Good point, this is fixed now.

**Comment by cristian-spissack** [comment]
+1 for replacing Socket.io with something more lightweight :)

**Comment by aromot** [comment]
I have the same problem. How to replace socket.io with SockJS?

**Comment by SpaceK33z** [comment]
@aromat, you'll have to wait until this PR is merged and released.

**Comment by mathieumg** [comment]
@SpaceK33z This would be a welcome change! Is there some sort of built version somewhere, or is using https://github.com/CodeYellowBV/webpack-dev-server/tree/sockjs as the dependency sufficient? What versions of Node are supported?

File: lib/Server.js [hunk 2]
```diff
@@ -146,7 +151,7 @@ function Server(compiler, options) {
 							}
 							proxy.web(req, res, proxyOptions, function(err){
 								var msg = "cannot proxy to " + proxyOptions.target + " (" + err.message + ")";
-								this.io.sockets.emit("proxy-error", [msg]);
+								this.sockWrite("proxy-error", [msg]);
```
Comment (mathieumg) [inline lib/Server.js]: Should this also be guarded with a verification that `this.sock` exists? I get a crash when this runs because `this.sock` is undefined in the `this.sockWrite` call. Perhaps that guard should simply be put inside the `sockWrite` call?

**Comment by SpaceK33z** [comment]
@mathieumg Looking at the `package.json` of webpack-dev-server, it runs a `prepublish` script. So that would mean you need a pre-built version.

You could test it manually by adding my github repo as a dependency, `npm install`-ing and running `npm run prepublish` in `node_modules/webpack-dev-server`. This would be only to test this PR of course. I would really like it if you do this, because this PR is relatively big. Please report your findings here :).

I can't find the exact node version requirements for the `sockjs-node` package, but it works fine for at least `v0.12` and `v4.x`.

**Comment by mathieumg** [comment]
Yeah I had figured that in the meantime! :) I did and I got a crash, I pointed where in the review, above!

**Comment by SpaceK33z** [comment]
@mathieumg, could you try again? I have probably fixed your issue. Weirdly enough I never had this issue.

**Comment by mathieumg** [comment]
@SpaceK33z Everything works perfectly with the latest fix! :)

**Comment by nelix** [comment]
What about server sent events, should be simpler and a small dependency for one way notifications.

https://github.com/glenjamin/webpack-hot-middleware uses SSE and the code looks really simple.

SSE should be easy to polyfill anywhere that has http.

**Comment by cristian-spissack** [comment]
@sokra Could we hear your opinion on this PR? It would solve the issue with dependency on the github package from socket.io and would be more lightweight.

File: lib/Server.js [hunk 3]
```diff
@@ -23,15 +23,22 @@ function Server(compiler, options) {
 	this.hot = options.hot;
 	this.headers = options.headers;
 
+	this.sockWrite = function(type, data) {
+		if (this.sock) {
+			this.sock.write(JSON.stringify({type: type, data: data}));
+		}
+	}
```
Comment (sokra) [inline lib/Server.js]: Could you move this function into the prototype of the class?

File: lib/Server.js (hunk 2 above)
Comment (sokra) [inline lib/Server.js]: There is a guard inside of `sockWrite`

File: client/live.js [hunk 4]
```diff
@@ -1,8 +1,37 @@
...
+		// Try to reconnect.
+		sock = null;
+		setTimeout(function () {
+			newConnection(handlers);
+		}, 2000);
+	};
+
+	sock.onopen = function() {
+		// This callback also fires on a reconnect.
+		handlers.ok();
```
Comment (sokra) [inline client/live.js]: Why doesn't a connect fires a `ok`? This should come from the server.

File: lib/Server.js (hunk 2 above)
Comment (mathieumg) [inline lib/Server.js]: Yes, it was added following my remark. :)

File: client/live.js (hunk 4 above)
Comment (SpaceK33z) [inline client/live.js]: On a normal open `ok` comes from the server. However, when the socket gets disconnected and reconnected again, it does not fire an `ok`. So the only way I found to work around this is to call the `ok` function when the socket connection is opened.

File: lib/Server.js (hunk 3 above)
Comment (SpaceK33z) [inline lib/Server.js]: Good point, fixed that now.

File: lib/Server.js [hunk 5]
```diff
@@ -264,24 +265,41 @@ Server.prototype.setContentHeaders = function(req, res, next) {
...
+		log: function(severity, line) {
+			if (severity === 'error') {
+				console.log(line);
+			}
+		}
 	});
-	this.io.sockets.on("connection", function(socket) {
-		if(this.hot) socket.emit("hot");
+	sockServer.on("connection", function(conn) {
+		this.sock = conn;
```
Comment (sokra) [inline lib/Server.js]: It should be possible to connect multiple devices to the same dev-server.

File: lib/Server.js (hunk 2 above)
Comment (sokra) [inline lib/Server.js]: :+1:

File: client/live.js (hunk 4 above)
Comment (sokra) [inline client/live.js]: > reconnected again, it does not fire an ok

Why not? On the server it `sendStats` on `connection`. Doesn't that work?

**Comment by eladh** [comment]
hi @SpaceK33z 

also checked the fix and the webpack dev server is up and running on windows.

any idea when the fixed will be merged and published ? 

10x

File: lib/Server.js (hunk 5 above)
Comment (SpaceK33z) [inline lib/Server.js]: Ah good point, this could also be the reason that a re-connect doesn't emit an `ok`.

File: client/live.js (hunk 4 above)
Comment (SpaceK33z) [inline client/live.js]: Ah, I had a bug in `lib/Server.js`. I have deleted these lines now :).

File: lib/Server.js (hunk 5 above)
Comment (SpaceK33z) [inline lib/Server.js]: Wow, that was a pretty big oversight of me. Pretty ashamed I didn't notice that myself. Anyway, it should be fixed now.

**Comment by SpaceK33z** [comment]
@eladh, I have now fixed @sokra's concerns, but I can't tell you when it's getting published of course.

**Comment by sokra** [comment]
Looks fine now... I'll test it and eventually merge it. Please ping me in a week if I forget it...

**Comment by 274793580** [comment]
+1 wait for it.

**Comment by eladh** [comment]
Important update - in the latest version of Artifactory there is support for this kind of problems (direct http or github resources)  via the NPM/Bower

https://www.jfrog.com/jira/browse/RTFACT-7664

**Comment by sokra** [comment]
Thanks :+1: 

pretty good change, finally we get rid of the native dependency...

**Comment by cristian-spissack** [comment]
Great job guys! Thank you!

**Comment by mathieumg** [comment]
Awesome! :tada:

**Comment by eladh** [comment]
thanks :-)

**Comment by abzainuddin** [comment]
\o/

**Comment by 274793580** [comment]
thanks

**Comment by fusepilot** [comment]
How does this fix #276? Theres still a ton of client side logging and I dont see how to disable it.

screenshot 2015-12-03 00 59 45

**Comment by SpaceK33z** [comment]
Yeah that's because you have enabled it in your `localStorage`. Open the console and type: `localStorage.removeItem('debug')`

**Comment by fusepilot** [comment]
That was it, thanks!

File: client/live.js [hunk 6]
```diff
@@ -1,8 +1,32 @@
...
+var SockJS = require("sockjs-client");
 var stripAnsi = require('strip-ansi');
 require("./style.css");
 
+var sock = null;
+var hot = false;
+var currentHash = "";
+
+var newConnection = function(handlers) {
+	sock = new SockJS('/sockjs-node');
```
Comment (jeffchan) [inline client/live.js]: Just wanted to flag that this breaks certain usage that relied on the previous `/socket.io` path. They now have to be `/sockjs-node`. Should this have been a major version bump, according to semver?

**Comment by muzishuiji** [comment]
i still do not know how to solve my trouble, it means that i should get the latest version of webpack-dev-server? or?
